Page({

  /**
   * 页面的初始数据
   */
  data: {
    hot: {},
    news: {},
    entertainment: {},
    windowHeight: 0,
    scrollTop: 0, //滑动的距离
    navFixed: false, //导航是否固定
    currentData: 0
  },

  getHot: function () {
    var hot_data = [
      {
        id:3,
        index_color:'#ff476f',
        index_font_style:'',
        index_text:'↑',        
        title:'看中国式现代化图景',
        num:'',
        type:'3',
        type_bg_color:'#FFA500',
        type_name:'热',
      },
      {
        id:1,
        index_color:'#ff476f',
        index_font_style:'oblique',
        index_text:'1',
        title:'考研成绩',
        num:'2600566',
        type:'1',
        type_bg_color:'#a50101',
        type_name:'爆',
      },
      {
        id:2,
        index_color:'#ff476f',
        index_font_style:'oblique',
        index_text:'2',
        title:'走进区域看发展',
        num:'1756485',
        type:'2',
        type_bg_color:'#ff476f',
        type_name:'新',
      },
      {
        id:4,
        index_color:'#ff476f',
        index_font_style:'oblique',
        index_text:'3',
        title:'考研国家线',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:5,
        index_color:'#FFA500',
        index_font_style:'',
        index_text:'·',
        title:'淡系女生变美思路',
        num:'1756485',
        type:'',
        type_bg_color:'#50aeff',
        type_name:'好物',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'5',
        title:'四六级查分',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'6',
        title:'up新时代中国',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'7',
        title:'二月二 辉山牛抬头',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'8',
        title:'情侣报考同校同专业考出同分',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'9',
        title:'重紫超话翻牌手绘乌龟',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'10',
        title:'孙俪罗晋 乌云之上',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'11',
        title:'如何看待拜登访乌？外交部回应',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'12',
        title:'多地学校因新冠甲流停课 专家回应',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'13',
        title:'文旅新气象，释放新活力',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'14',
        title:'林志颖刘荷娜16年后同框',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'15',
        title:'考研成绩',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'16',
        title:'41万元的网红摊位或15天回本',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'17',
        title:'“上岸”被抢注商标',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'18',
        title:'女子无意找到30多年前的钱包',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'19',
        title:'老牌国货公司隆力奇人去楼空',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'20',
        title:'贪官家庭会议设秘书长 婴儿也参会',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'21',
        title:'泽连斯基站在拜登身后悄悄抹泪',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'22',
        title:'日本66%的高端外国人才是中国人',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'23',
        title:'男子多次猥亵女子称自己易冲动',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'24',
        title:'辽宁盘锦教育局局长因意外去世',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'25',
        title:'未婚夫去世准公公写信求留下孩子',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'26',
        title:'高圆圆的仪态',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'27',
        title:'狂飙京海医院窗外是爱情公寓',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'28',
        title:'今晚能看到真正的龙抬头',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'29',
        title:'网购iPhone14开箱发现是IQOO',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'30',
        title:'女子住着大别墅欠5000不还成老赖',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'31',
        title:'情侣备考同校同专业考出同分',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'32',
        title:'男子发现亡父739万债务3年偿清',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'33',
        title:'鞠婧祎象征性的剪两根头发',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'34',
        title:'种地吧 开公司',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'35',
        title:'广东一病例高烧不退潜伏45天',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'36',
        title:'边伯贤剧透EXO新歌歌词',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'37',
        title:'党和国家机构改革方案',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'38',
        title:'秦刚谈乌克兰问题：停止甩锅中国',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'39',
        title:'男孩在顶楼玩耍疑踩空从32楼坠亡',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'40',
        title:'女孩知道一年学费5万哭成泪人',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'41',
        title:'女子拒接反诈电话被骗122万',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'42',
        title:'起底近年来网暴致死案幕后黑手',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'43',
        title:'贪官家庭会议设秘书长 婴儿也参会',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'44',
        title:'泽连斯基站在拜登身后悄悄抹泪',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'45',
        title:'未婚夫去世准公公写信求留下孩子',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'46',
        title:'日本66%的高端外国人才是中国人',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'47',
        title:'男孩在顶楼玩耍疑踩空从32楼坠亡',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'48',
        title:'女孩知道一年学费5万哭成泪人',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'49',
        title:'异地恋接吻神器你会买吗',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      },
      {
        id:6,
        index_color:'#FFA500',
        index_font_style:'oblique',
        index_text:'50',
        title:'章子怡 中戏考官',
        num:'1756485',
        type:'',
        type_bg_color:'',
        type_name:'',
      }
    ];
    this.setData({
      hot: hot_data
    });
  },

  getEntertainment: function () {
    let hot = this.data.hot;
    
    hot.sort(function () {
      return Math.random() - 0.5
    })

    this.setData({
      entertainment: hot
    });
  },

  getNews: function () {
    let news = this.data.hot;
    
    news.sort(function () {
      return Math.random() - 0.5
    })

    this.setData({
      news: news
    });
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    this.getHot();
    this.getEntertainment();
    this.getNews();
  },
  //点击切换，滑块index赋值
  checkCurrent: function (e) {
    console.log('点击切换')
    console.log(e.target.dataset.current)
    if (this.data.currentData === e.target.dataset.current) {
      return false;
    } else {
      this.setData({
        currentData: e.target.dataset.current
      })
    }
  },

  //监听滑动
  layoutScroll: function (e) {
    this.data.scrollTop = this.data.scrollTop * 1 + e.detail.deltaY * 1;
    // console.log(this.data.scrollTop)
    // console.log(this.data.navFixed)

    /** 我这里写了固定值 如果使用rpx 可用query可以动态获取其他的高度 然后修改这里值 */
    /** 获取方法参考文档 */

    /** scrollTop 在模拟器上检测不是太灵敏 可在真机上测试 基本上不会出现延迟问题 */
    var navtopHeight = 160;
    if (this.data.scrollTop <= -navtopHeight) {
      this.setData({
        navFixed: true
      })
    } else {
      this.setData({
        navFixed: false
      })
    }
  },
})
